In [1]:
import numpy as np
from scipy import stats


# Задача 1

In [16]:
# Таблица сопряженности
obs = np.array([[197, 158], [102, 221]])
obs

array([[197, 158],
       [102, 221]])

In [23]:
# расчет статистики критерия Хи квадрат
(197 - 355 * 299 / 678)**2 / (355 * 299 / 678) + (158 - 355 * 379 / 678)**2 / (355 * 379 / 678) + \
(102 - 323 * 299 / 678)**2 / (323 * 299 / 678) + (221 - 323 * 379 / 678)**2 / (323 * 379 / 678)

39.23331432611949

In [32]:
# Критерий Хи квадрат Пирсона
stats.chi2_contingency(obs)

(38.26924442054285,
 6.162631103993754e-10,
 1,
 array([[156.5560472, 198.4439528],
        [142.4439528, 180.5560472]]))

In [22]:
# Нормированные коэффициенты
chi2 = stats.chi2_contingency(obs)[0]
n = np.sum(obs)
k = obs.shape[0]
m = obs.shape[1]

tschuprow = np.sqrt(chi2 / (n * np.sqrt((k - 1) * (m - 1))))
cramer = np.sqrt(chi2 / (n * (np.minimum(k, m) - 1)))
pearson = np.sqrt(chi2 / (n + chi2))

print(tschuprow)
print(cramer)
print(pearson)

0.23758011975886253
0.23758011975886253
0.23114621806808983


In [25]:
# Расчет коэффициента контингеции
(197 * 221 - 102 * 158) / np.sqrt(355 * 323 * 299 * 279)

0.280369105000437

In [26]:
# Расчет коэффициента ассоциации Юла
(197 * 221 - 102 * 158) / (197 * 221 + 102 * 158)

0.4596751211171274

# Задача 2

In [28]:
# расчет критерия спирмена
S = (8-10)**2 + (2-7)**2 + (9-8)**2 + (6-2)**2 + (4-5)**2 + (5-1)**2 + (3-6)**2 + (7-3)**2 + (10-9)**2 + (1-4)**2
ro = 1 - (6 * S / (10**3 - 10))
T = np.sqrt(10 - 1) * ro
T

1.218181818181818

In [55]:
ro

0.406060606060606

In [56]:
x = np.array([8,2,9,6,4,5,3,7,10,1])
y = np.array([10,7,8,2,5,1,6,3,9,4])


In [33]:
# Коэффициент Спирмена
stats.spearmanr(x, y)

SpearmanrResult(correlation=0.406060606060606, pvalue=0.24428229408662638)

In [34]:
# Коэффициент Keндалла
stats.kendalltau(x, y)

KendalltauResult(correlation=0.24444444444444444, pvalue=0.38071979717813054)

In [36]:
stats.kendalltau(a, b)

KendalltauResult(correlation=-0.9999999999999999, pvalue=0.016666666666666666)

# Задача 3

In [65]:
X = np.array([66,61,67,73,51,59,48,47,58,44,41,54,52,47,51,45])
Y = np.array([38,31,36,43,29,33,28,25,36,26,21,30,20,27,28,26])

In [43]:
# Статистика выборочного коэффициента корреляции
Xav = X.mean()
Yav = Y.mean()
ch = 0
zn1 = 0
zn2 = 0
for i in range(len(X)):
    ch += (X[i] - Xav) * (Y[i] - Yav)
    zn1 += (X[i] - Xav)**2
    zn2 += (Y[i] - Yav)**2
r = ch / np.sqrt(zn1 * zn2)
T = r * np.sqrt(len(X) - 2) / np.sqrt(1 - r**2)
T

7.279263791858351

In [40]:
# Выборочная корреляция
stats.pearsonr(X,Y)

(0.8893853779200405, 4.036815535474195e-06)

In [71]:
# Статистика ранговой корреляции Спирмана
S1 = 0
for i in range(len(X)):
    S1 += (X.argsort().argsort()[i] - Y.argsort().argsort()[i])**2
ro1 = 1 - (6 * S1 / (len(X)**3 - len(X)))
T1 = np.sqrt(len(X) - 1) * ro1
T1

3.3148180992539955

In [51]:
# Коэффициент Спирмана
stats.spearmanr(X , Y)

SpearmanrResult(correlation=0.8583028167652765, pvalue=2.096824258861966e-05)

In [75]:
# Коэффициент Keндалла
stats.kendalltau(X, Y)

KendalltauResult(correlation=0.7404322357228396, pvalue=8.25894556613836e-05)

In [78]:
# Переход к номинальной шкале
def to_nominal(X,Y,N):
    x_step = (max(X) - min(X)) / N
    y_step = (max(Y) - min(Y)) / N
    x = min(X)
    y = min(Y)
    n = len(X)
    nom =[]
    while x < max(X):
        row = []
        y = min(Y)
        while y < max(Y):
            count = 0
            for i in range(n):
                if (X[i] >= x) & (X[i] < x + x_step) & (Y[i] >= y) & (Y[i] < y + y_step):
                    count += 1
            row.append(count)
            y += y_step
        nom.append(row)
        x += x_step
    nom[N - 1][N - 1] += 1
    return np.array(nom)
contin =  to_nominal(X, Y, 2)
contin

array([[10,  0],
       [ 1,  5]])

In [86]:
# расчет статистики критерия Хи квадрат
((10 - 10 * 11 / 16)**2) / (10 * 11 / 16) + ((0 - 10 * 5 / 16)**2) / (10 * 5 / 16) + \
((1 - 11 * 6 / 16)**2) / (11 * 6 / 16) + ((5 - 6 * 5 / 16)**2) / (6 * 5 / 16)

12.121212121212121

In [81]:
# Критерий Хи квадрат Пирсона
stats.chi2_contingency(contin)

(8.552727272727271,
 0.003450049583251144,
 1,
 array([[6.875, 3.125],
        [4.125, 1.875]]))