# Задание 1

In [15]:
def scal (x,y):
    if len(x) == len(y):
        n = len(x)
        summ = 0
        for i in range(n):
            summ += x[i] * y[i]
    else: summ = 'Вектора имеют разную длину'
    return summ        

def konst (x,y):
    n = len(x)
    X = []
    for i in range(n):
        X.append(x[i] * y) 
    return X

        

In [17]:
# 1. 
a1 = [2, 5, 0, 6, 8, 10, 6, 7, 5, 7]
b1 = [8, 6, 7, 9, 6 ,6 , 2, 3, 2 , 3]
f1 = scal(konst(a1,3),konst(b1,2))
f1

1632

In [18]:
# 2. 
a2 = [9, 6, 7, 7 ,0 , 1, 6, 8, 1, 2]
b2 = [0, 2, 2, 6, 7, 8, 8, 3, 1, 8]
f2 = scal(konst(a2,6),konst(b2,5))
f2

4950

In [19]:
# 3. 
a3 = [2, 5, 0, 6, 8, 10, 6, 7, 5, 7]
b3 = [8, 6, 7, 9, 6, 6, 2, 3, 2, 3]
f3 = scal(konst(a3,1),konst(b3,1))
f3

272

In [20]:
# 4. 
a4 = [9, 6, 7, 7, 0, 1, 6, 8, 1, 2]
b4 = [0, 2, 2, 6, 7, 8, 8, 3, 1, 8]
f4 = scal(konst(a4,1),konst(b4,1))
f4

165

# Задание 2

In [1]:
import numpy as np

In [6]:
def trans (X):

    n1 = X.shape[0]
    n2 = X.shape[1]
    arr = np.empty((n2,n1), dtype="int")
    for i in range(n2):
        for j in range(n1):
            arr[i][j] = X[j][i]

    return arr

In [2]:
A = np.array([[2,1,7,4],
             [5,6,7,3],
             [9,8,2,12],
             [11,14,15,15]])
A

array([[ 2,  1,  7,  4],
       [ 5,  6,  7,  3],
       [ 9,  8,  2, 12],
       [11, 14, 15, 15]])

In [128]:
trans(A)

array([[ 2,  5,  9, 11],
       [ 1,  6,  8, 14],
       [ 7,  7,  2, 15],
       [ 4,  3, 12, 15]])

In [3]:
B = np.array([[3,7,8,3,6],
              [2,5,9,4,13]])
B

array([[ 3,  7,  8,  3,  6],
       [ 2,  5,  9,  4, 13]])

In [9]:
trans(B)

array([[ 3,  2],
       [ 7,  5],
       [ 8,  9],
       [ 3,  4],
       [ 6, 13]])

In [17]:
C = np.array([[-2,4], [3,7]])
display(C)
np.linalg.inv(C)


array([[-2,  4],
       [ 3,  7]])

array([[-0.26923077,  0.15384615],
       [ 0.11538462,  0.07692308]])

In [18]:
C = np.array([[8,1], [5,3]])
display(C)
np.linalg.inv(C)

array([[8, 1],
       [5, 3]])

array([[ 0.15789474, -0.05263158],
       [-0.26315789,  0.42105263]])

In [21]:
D = np.array([[2,5], [7,-3]])
E = np.array([[11],[-23]])
display(D)
display(E)
Dinv = np.linalg.inv(D)
X = Dinv.dot(E)
X

array([[ 2,  5],
       [ 7, -3]])

array([[ 11],
       [-23]])

array([[-2.],
       [ 3.]])

In [23]:
D = np.array([[-3,1], [3,5]])
E = np.array([[-2],[8]])
display(D)
display(E)
Dinv = np.linalg.inv(D)
X = Dinv.dot(E)
X

array([[-3,  1],
       [ 3,  5]])

array([[-2],
       [ 8]])

array([[1.],
       [1.]])

In [24]:
D = np.array([[2,3], [3,-1]])
E = np.array([[12],[7]])
display(D)
display(E)
Dinv = np.linalg.inv(D)
X = Dinv.dot(E)
X

array([[ 2,  3],
       [ 3, -1]])

array([[12],
       [ 7]])

array([[3.],
       [2.]])

# Задача 3

In [131]:
from sympy import *

In [132]:
a1, a2 = symbols('a1, a2')
MSE = (1/4) * ((1*a1 + 2*a2 - 5)**2 + (5*a1 + 3*a2 - 6)**2 + (2*a1 + 4*a2 - 10)**2 + (3*a1 + 7*a2 - 8)**2)
MSE

0.25*(a1 + 2*a2 - 5)**2 + 0.25*(2*a1 + 4*a2 - 10)**2 + 0.25*(3*a1 + 7*a2 - 8)**2 + 0.25*(5*a1 + 3*a2 - 6)**2

In [133]:
MSEa2 = diff(MSE,a2)
MSEa1 = diff(MSE,a1)
display(MSEa2)
display(MSEa1)

23.0*a1 + 39.0*a2 - 62.0

19.5*a1 + 23.0*a2 - 39.5

In [134]:
eq = linsolve([MSEa2, MSEa1], (a2, a1))
eq

{(1.29805615550756, 0.494600431965443)}

In [135]:
MSE.subs({'a2': eq.args[0][0], 'a1': eq.args[0][1]})

6.24190064794816

In [136]:
MSE.subs({'a2': 0, 'a1': 0})

56.2500000000000

In [140]:
GrMSE = np.array([MSEa1,MSEa2])
GrMSE

array([19.5*a1 + 23.0*a2 - 39.5, 23.0*a1 + 39.0*a2 - 62.0], dtype=object)

In [166]:
A_1 = 0
A_2 = 0
n = 0
while MSE.subs({'a2': A_2, 'a1': A_1}) > 6.36:
    n += 1
    a_1, a_2 = A_1, A_2
    A_1 += -MSEa1.subs({'a2': a_2, 'a1': a_1}) * 0.01
    A_2 += -MSEa2.subs({'a2': a_2, 'a1': a_1}) * 0.01
print(f'Всего итераций: {n}')
print(f"Значение MSE: {MSE.subs({'a2': A_2, 'a1': A_1})} в точке ({A_1}, {A_2})")
    

Всего итераций: 7
Значение MSE: 6.35010849011797 в точке (0.678414954289931, 1.16948998651869)
